### ISSUE TITLE
info error with included catalog.xml

### ISSUE THREAD

**Issue by depify** [ndw/xmlcalabash1-xmlunit#1] opened 2015-06-01 05:58 UTC
when this step is installed with depify and then run test pipeline I get successful output though with precedent log output

```
INFO : I/O error reading catalog URI in jar file: jar:file://lib/xmlcalabash1-xmlunit-1.1.2/xmlcalabash1-xmlunit-1.1.2.jar!/catalog.xml
```

I suspect this affects all the xmlcalabash1- extension steps

**Comment by ndw** [comment] 2015-06-01 15:39
I can't reproduce that outside of depify. Can you send me a more detailed recipe to reproduce, please?

**Comment by depify** [comment] 2015-06-01 16:26
just do 

depify install xmlcalabash1-xmlunit

and try to run example test with xproc.sh

**Comment by ndw** [comment] 2015-06-01 16:32
Failed to reproduce. Closing at Jim's request.

**Closed as completed by ndw** 2015-06-01 16:32 UTC
